apiVersion: v1
kind: Service
metadata:
  name: python-docker-service
spec:
  selector:
    app: python-docker-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
